// scripts/review-call.js
// Multi-provider PR review caller — OpenAI-compatible & Anthropic endpoints.
// Captures and sends the real git diff to the configured LLM.

const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');
const { execSync } = require('child_process');

function getPrDiff(pr) {
  // 1. Check if /tmp/pr.diff was pre-generated by the workflow step
  if (fs.existsSync('/tmp/pr.diff')) {
    const fromFile = fs.readFileSync('/tmp/pr.diff', 'utf8').trim();
    if (fromFile) return fromFile;
  }

  // 2. Try git diff using PR base and head SHAs
  const baseSha = pr && pr.base && pr.base.sha ? pr.base.sha : process.env.BASE_SHA;
  const headSha = pr && pr.head && pr.head.sha ? pr.head.sha : (process.env.HEAD_SHA || 'HEAD');

  if (baseSha) {
    try {
      const out = execSync(`git diff ${baseSha}...${headSha} 2>/dev/null || git diff ${baseSha} ${headSha} 2>/dev/null`, {
        maxBuffer: 15 * 1024 * 1024,
        encoding: 'utf8'
      }).trim();
      if (out) return out;
    } catch (_) {}
  }

  // 3. Fallback: git diff against parent or staged/working tree
  try {
    const out = execSync('git diff HEAD~1 2>/dev/null || git diff --cached 2>/dev/null || git diff 2>/dev/null', {
      maxBuffer: 15 * 1024 * 1024,
      encoding: 'utf8'
    }).trim();
    if (out) return out;
  } catch (_) {}

  // 4. Fallback: gh pr diff if CLI is authenticated
  const prNum = process.env.PR_NUMBER || (pr && pr.number);
  const repo = process.env.REPO || process.env.GITHUB_REPOSITORY;
  if (prNum) {
    try {
      const repoArg = repo ? `--repo "${repo}"` : '';
      const out = execSync(`gh pr diff "${prNum}" ${repoArg} 2>/dev/null`, {
        maxBuffer: 15 * 1024 * 1024,
        encoding: 'utf8'
      }).trim();
      if (out) return out;
    } catch (_) {}
  }

  return '';
}

function resolveProvider() {
  const reqProvider = (process.env.LLM_PROVIDER || 'minimax').toLowerCase();

  if (reqProvider === 'minimax') {
    const key = process.env.MINIMAX_API_KEY;
    const base = (process.env.MINIMAX_BASE_URL || 'https://api.minimax.chat/v1').replace(/\/$/, '');
    const model = process.env.MINIMAX_MODEL || 'MiniMax-M3';
    return { name: 'minimax', key, base, model, format: 'openai' };
  }

  if (reqProvider === 'openai') {
    const key = process.env.OPENAI_API_KEY;
    const base = (process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1').replace(/\/$/, '');
    const model = process.env.OPENAI_MODEL || 'gpt-4o-mini';
    return { name: 'openai', key, base, model, format: 'openai' };
  }

  if (reqProvider === 'gemini') {
    const key = process.env.GOOGLE_API_KEY || process.env.GEMINI_API_KEY;
    const base = (process.env.GEMINI_BASE_URL || 'https://generativelanguage.googleapis.com/v1beta/openai').replace(/\/$/, '');
    const model = process.env.GEMINI_MODEL || 'gemini-2.0-flash';
    return { name: 'gemini', key, base, model, format: 'openai' };
  }

  if (reqProvider === 'anthropic') {
    const key = process.env.ANTHROPIC_API_KEY;
    const base = (process.env.ANTHROPIC_BASE_URL || 'https://api.anthropic.com/v1').replace(/\/$/, '');
    const model = process.env.ANTHROPIC_MODEL || 'claude-3-5-sonnet-latest';
    // If custom base (e.g. OpenAI proxy), use openai format; otherwise native anthropic
    const format = base.includes('anthropic.com') ? 'anthropic' : 'openai';
    return { name: 'anthropic', key, base, model, format };
  }

  // Fallback heuristic: check available keys
  if (process.env.MINIMAX_API_KEY) {
    return { name: 'minimax', key: process.env.MINIMAX_API_KEY, base: 'https://api.minimax.chat/v1', model: 'MiniMax-M3', format: 'openai' };
  }
  if (process.env.OPENAI_API_KEY) {
    return { name: 'openai', key: process.env.OPENAI_API_KEY, base: 'https://api.openai.com/v1', model: 'gpt-4o-mini', format: 'openai' };
  }
  if (process.env.GOOGLE_API_KEY || process.env.GEMINI_API_KEY) {
    return { name: 'gemini', key: process.env.GOOGLE_API_KEY || process.env.GEMINI_API_KEY, base: 'https://generativelanguage.googleapis.com/v1beta/openai', model: 'gemini-2.0-flash', format: 'openai' };
  }

  return { name: reqProvider, key: null, base: '', model: '', format: 'openai' };
}

function loadReviewPrompt() {
  const candidatePaths = [
    path.join(__dirname, '..', 'prompts', 'review.md'),
    path.join(__dirname, 'prompts', 'review.md'),
    '/tmp/gatling-prompts/review.md'
  ];
  for (const p of candidatePaths) {
    if (fs.existsSync(p)) {
      return fs.readFileSync(p, 'utf8');
    }
  }
  return `You are a senior code reviewer reviewing a pull request diff.
Project conventions:
- Prefer findings that map to specific files and lines.
- Skip findings about pure formatting, comments, or import order unless they violate stated style.
- Output format: markdown comment with findings (severity, file:line, issue, suggested fix).
End with LGTM, Approve with suggestions, or Request changes.`;
}

function postHttpRequest(targetUrl, headers, payload) {
  return new Promise((resolve, reject) => {
    const parsed = new URL(targetUrl);
    const client = parsed.protocol === 'http:' ? http : https;
    const req = client.request(parsed, {
      method: 'POST',
      headers
    }, res => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => resolve({ statusCode: res.statusCode, body: data }));
    });
    req.on('error', reject);
    req.write(payload);
    req.end();
  });
}

(async () => {
  const provider = resolveProvider();
  if (!provider.key) {
    console.log(`[ai-review] No API key configured for provider "${provider.name}" — skipping AI review.`);
    process.exit(0);
  }

  // Load PR metadata
  const event = process.env.GITHUB_EVENT_PATH && fs.existsSync(process.env.GITHUB_EVENT_PATH)
    ? JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8'))
    : null;
  const pr = event ? event.pull_request : null;

  // Capture real diff
  let diff = getPrDiff(pr);
  if (!diff) {
    console.log('[ai-review] No code diff detected between base and head — skipping review.');
    process.exit(0);
  }

  // Truncate diff if exceptionally large
  const maxDiffLength = 30000;
  let truncatedNotice = '';
  if (diff.length > maxDiffLength) {
    diff = diff.slice(0, maxDiffLength);
    truncatedNotice = `\n\n[Note: diff truncated to first ${maxDiffLength} characters for review]`;
  }

  const promptTemplate = loadReviewPrompt();
  const prTitle = pr && pr.title ? pr.title : (process.env.PR_TITLE || 'Untitled PR');
  const prBody = pr && pr.body ? pr.body.slice(0, 1500) : '';

  const userContent = `${promptTemplate}\n\n---\n\n` +
    `PR Title: ${prTitle}\n` +
    (prBody ? `PR Description:\n${prBody}\n\n` : '') +
    `--- GIT DIFF ---\n\`\`\`diff\n${diff}\n\`\`\`${truncatedNotice}\n\n` +
    `Please provide a concise code review adhering to the rules above.`;

  let responseText = '';
  console.log(`[ai-review] Requesting review from ${provider.name} (model: ${provider.model}) with ${diff.length} bytes diff...`);

  try {
    if (provider.format === 'anthropic') {
      const payload = JSON.stringify({
        model: provider.model,
        max_tokens: 1500,
        temperature: 0.2,
        messages: [{ role: 'user', content: userContent }]
      });
      const res = await postHttpRequest(`${provider.base}/messages`, {
        'x-api-key': provider.key,
        'anthropic-version': '2023-06-01',
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(payload)
      }, payload);

      if (res.statusCode !== 200) {
        console.error(`[ai-review] Anthropic API error ${res.statusCode}: ${res.body.slice(0, 300)}`);
        process.exit(0);
      }
      const data = JSON.parse(res.body);
      responseText = data.content?.[0]?.text || '';
    } else {
      // OpenAI-compatible (/chat/completions)
      const payload = JSON.stringify({
        model: provider.model,
        max_tokens: 1500,
        temperature: 0.2,
        messages: [
          { role: 'system', content: 'You are a senior code reviewer providing GitHub PR review comments.' },
          { role: 'user', content: userContent }
        ]
      });
      const res = await postHttpRequest(`${provider.base}/chat/completions`, {
        'Authorization': `Bearer ${provider.key}`,
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(payload)
      }, payload);

      if (res.statusCode !== 200) {
        console.error(`[ai-review] LLM API error ${res.statusCode}: ${res.body.slice(0, 300)}`);
        process.exit(0);
      }
      const data = JSON.parse(res.body);
      responseText = data.choices?.[0]?.message?.content || '';
    }

    if (!responseText) {
      console.log('[ai-review] Empty response received from model.');
      process.exit(0);
    }

    fs.writeFileSync('/tmp/review.md', responseText);
    console.log(`[ai-review] Review generated (${responseText.length} characters) written to /tmp/review.md`);

    // Post to PR if PR_NUMBER and token are present
    const prNumber = process.env.PR_NUMBER || (pr && pr.number);
    const ghToken = process.env.GH_TOKEN || process.env.GITHUB_TOKEN;
    const repo = process.env.REPO || process.env.GITHUB_REPOSITORY;

    if (prNumber && ghToken) {
      try {
        const repoArg = repo ? `--repo "${repo}"` : '';
        execSync(`gh pr comment "${prNumber}" ${repoArg} --body-file /tmp/review.md`, {
          stdio: 'inherit',
          env: { ...process.env, GH_TOKEN: ghToken }
        });
        console.log(`[ai-review] Review comment posted to PR #${prNumber}`);
      } catch (err) {
        console.warn(`[ai-review] Could not post comment via gh: ${err.message}`);
      }
    }
  } catch (err) {
    console.error(`[ai-review] Request failed: ${err.message}`);
    process.exit(0);
  }
})();
